tutorial/tutorial/urls.py
# from django.conf.urls import include, url
# from django.contrib import admin
# from community.views import *

# urlpatterns = [
#     url(r'^admin/', include(admin.site.urls)),
#     url(r'^write/', write, name='write'),
# ]

# from django.conf.urls import url
# from django.contrib import admin
# from community.views import *
from django.contrib import admin
from django.urls import path, include
from community.views import *

urlpatterns = [
    path('bbs/', list, name='list'),
    #path('bbs/view/(?P<num>[0-9]+)', view, name='view'),
    path('bbs/view/<num>/', view, name='view'),
    path('bbs/edit/<num>/', edit, name='edit'),
    path('bbs/write/', write, name='write'),
    path('admin/', admin.site.urls),
]

tutorial/community/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    name = models.CharField(max_length=50)
    title = models.CharField(max_length=50)
    contents = models.TextField()
    url = models.URLField()
    email = models.EmailField()
    cdate = models.DateTimeField(auto_now_add=True)

tutorial/community/forms.py
from django.forms import ModelForm
from community.models import *

class Form(ModelForm):
    class Meta:
        model = Article
        fields=['name', 'title', 'contents','url', 'email']

tutorial/community/views.py
from django.shortcuts import redirect
from django.shortcuts import render
from community.forms import *

# Create your views here.
def write(request):
    if request.method == 'POST':
        form =Form(request.POST)
        if form.is_valid():
            form.save()
            return redirect(f'/bbs/')
    else:
        form =Form()

    return render(request, 'write.html', {'form':form})
    
def list(request):
    articleList = Article.objects.all()
    return render(request, 'list.html', {'articleList':articleList})

def view(request, num="1"):
    article = Article.objects.get(id=num)
    return render(request, 'view.html', {'article':article})

def edit(request, num="1"):
    article = Article.objects.get(id=num)
    if request.method == 'POST':
        article.name = request.POST['name']
        article.title = request.POST['title']
        article.contents = request.POST['contents']
        article.url = request.POST['url']
        article.email = request.POST['email']
        article.save()
        return redirect(f'/bbs/view/{ num }')
    return render(request, 'edit.html', {'article':article})

# def edit_feed(request, dj):
#     article = Article.object.get(dj=dj)
#     return render(request, 'edit_feed.html',{'feed': article})

tutorial/community/templates/edit.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>edit</title>
  </head>
  <body>
      <form action="" method="post">
        <p><label for="id_name">Name:</label> <input type="text" name="name" maxlength="50" required="" id="id_name" value="{{ article.name }}"></p>
        <p><label for="id_title">Title:</label> <input type="text" name="title" maxlength="50" required="" id="id_title" value="{{ article.title }}"></p>
        <p><label for="id_contents">Contents:</label> <textarea name="contents" cols="40" rows="10" required="" id="id_contents">{{ article.contents }}</textarea></p>
        <p><label for="id_url">Url:</label> <input type="url" name="url" maxlength="200" required="" id="id_url"value="{{ article.url }}"></p>
        <p><label for="id_email">Email:</label> <input type="email" name="email" maxlength="254" required="" id="id_email"value="{{ article.email }}"></p>
        <input type="hidden" name="csrfmiddlewaretoken" value="Gji1Rv5MrMh1btr4RhgL6DbkuJ9lpoPr3dp4X1BYJxHt0l6vZUGkkM89auPBKZg8">
        <button type="submit" class="btn btn-primary">저장</button>
        </form>
    <!--
    <form action="" method="post">
      {{ form.as_p }}
      {% csrf_token %}
    <button type="submit" class="btn btn-primary">저장</button>
    </form>
    -->
</body>
</html>

tutorial/community/templates/list.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>list</title> 
</head>
<body>
  <a href="/bbs/write">글쓰기</a>
  <ul>
      <li>제목 | 저자 | 날짜 | 수정</li>
      {% for article in articleList %}
      <li><a href="/bbs/view/{{ article.id }}">{{ article.title }}</a> | {{ article.name }} | {{ article.cdate|date:"D d M Y" }} | <a href="/bbs/edit/{{ article.id }}">Edit</a></li>
      {% endfor %}
  </ul>
</body>
</html>

tutorial/community/templates/view.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>view</title> 
</head>
<body>
    제목: {{ article.title }}
    <br>
    저자: {{ article.name }}
    <br>
    내용: {{ article.contents }}
    <br>
    이메일: {{ article.email }}
    <br>
    날짜: {{ article.cdate|date:"D d M Y" }}
    <br>
</body>
</html>

tutorial/community/templates/write.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>write</title>
  </head>
  <body>
    <form action="" method="post">
      {{ form.as_p }}
      {% csrf_token %}
    <button type="submit" class="btn btn-primary">저장</button>
    </form>
</body>
</html>